# Generated by Django 4.2.25 on 2025-10-06 03:46

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('cor', models.CharField(default='#6B7280', help_text='Cor em hexadecimal', max_length=7, verbose_name='Cor')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('company', models.ForeignKey(help_text='Empresa proprietária deste registro', on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Categoria Financeira',
                'verbose_name_plural': 'Categorias Financeiras',
                'ordering': ['tipo', 'nome'],
                'unique_together': {('company', 'nome', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome/Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, verbose_name='Nome Fantasia')),
                ('tipo_pessoa', models.CharField(choices=[('fisica', 'Pessoa Física'), ('juridica', 'Pessoa Jurídica')], max_length=10, verbose_name='Tipo de Pessoa')),
                ('cpf_cnpj', models.CharField(blank=True, help_text='Somente números (11 para CPF, 14 para CNPJ)', max_length=14, validators=[django.core.validators.RegexValidator(message='CPF deve ter 11 dígitos ou CNPJ deve ter 14 dígitos', regex='^\\d{11}$|^\\d{14}$')], verbose_name='CPF/CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, help_text='Somente números', max_length=20, verbose_name='Inscrição Estadual')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('company', models.ForeignKey(help_text='Empresa proprietária deste registro', on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('company', models.ForeignKey(help_text='Empresa proprietária deste registro', on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'ordering': ['nome'],
                'unique_together': {('company', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cnpj', models.CharField(help_text='Somente números (14 dígitos)', max_length=14, validators=[django.core.validators.RegexValidator(message='CNPJ deve conter exatamente 14 números', regex='^\\d{14}$')], verbose_name='CNPJ')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('company', models.ForeignKey(help_text='Empresa proprietária deste registro', on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiais',
                'ordering': ['nome'],
                'unique_together': {('company', 'cnpj')},
            },
        ),
        migrations.CreateModel(
            name='ContasPagar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Original')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Desconto')),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Juros')),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Multa')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor Pago')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('vencida', 'Vencida'), ('paga', 'Paga'), ('paga_parcial', 'Paga Parcialmente'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('e_parcelada', models.BooleanField(default=False, verbose_name='É Parcelada?')),
                ('parcela_atual', models.PositiveIntegerField(default=1, verbose_name='Parcela Atual')),
                ('total_parcelas', models.PositiveIntegerField(default=1, verbose_name='Total de Parcelas')),
                ('grupo_parcelamento', models.UUIDField(blank=True, help_text='ID que agrupa todas as parcelas', null=True, verbose_name='Grupo de Parcelamento')),
                ('e_recorrente', models.BooleanField(default=False, verbose_name='É Recorrente?')),
                ('frequencia_recorrencia', models.CharField(blank=True, choices=[('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20, null=True, verbose_name='Frequência de Recorrência')),
                ('notas_fiscais', models.CharField(blank=True, help_text='Ex: 123, 456, 789', max_length=200, validators=[django.core.validators.RegexValidator(message='Notas fiscais devem conter apenas números, vírgulas e espaços', regex='^[\\d,\\s]*$')], verbose_name='Notas Fiscais')),
                ('numero_boleto', models.CharField(blank=True, help_text='Somente números', max_length=100, validators=[django.core.validators.RegexValidator(message='Número do boleto deve conter apenas números', regex='^\\d*$')], verbose_name='Número do Boleto')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='contas_pagar/%Y/%m/', verbose_name='Anexo')),
                ('categoria', models.ForeignKey(limit_choices_to={'tipo': 'despesa'}, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='financeiro.categoriafinanceira', verbose_name='Categoria')),
                ('company', models.ForeignKey(help_text='Empresa proprietária deste registro', on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('filial', models.ForeignKey(help_text='Filial responsável por esta conta', on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='financeiro.filial', verbose_name='Filial')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='financeiro.formapagamento', verbose_name='Forma de Pagamento')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='financeiro.fornecedor', verbose_name='Fornecedor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['-data_vencimento', '-created_at'],
                'indexes': [models.Index(fields=['company', 'filial', 'status'], name='financeiro__company_138693_idx'), models.Index(fields=['company', 'filial', 'data_vencimento'], name='financeiro__company_4357f0_idx')],
            },
        ),
    ]
