# Generated by Django 4.2.25 on 2025-10-07 02:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaspagar',
            name='data_emissao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão'),
        ),
    ]
